### ISSUE TITLE
Mint autófelvevő azt akarom, hogy fel tudjak venni egy egyedi autótípust a rendszerbe, azért hogy azt az ügyfelek elérhessék, milyen típusú kocsikból lehet választani

### ISSUE THREAD

**Issue by rajnaig1** [KTRNinjas/Car-Rental#4]
## Fontosság
6
## Sprint pontérték
1
## Összes
7
## Elfogadási kritérium:
- [x] Legyen egy honlap az autóért felelős embernek, amin keresztül új autótípust tud felvenni az adatbázisba
- [x] Legyen egy autotipus tábla az adatbázisban, SQL scripttel létrehozva
- [x] A legördülő menük adatai (pl környezetvédelmi besorolás E6 E5 etc) SQL táblák legyenek, foreign keyvel kapcsolva az autotipus adatbázishoz
- [x] Legyen egy service és DAO amin keresztül a controller tud a db-vel kommunikálni 
- [x] Legyen egy külön kis adatbázistáblája a Fajtának, ami idegen kulccsal van rákapcsolva az autotípusra
- [x] Legyen egy külön kis adatbázistáblája a Fajtának, ami idegen kulccsal van rákapcsolva az autotípusra
- [x] Legyen egy külön kis adatbázistáblája a Kategória, ami idegen kulccsal van rákapcsolva az autotípusra
- [x] Legyen egy külön kis adatbázistáblája a Környezetvédelmi besorolásra, ami idegen kulccsal van rákapcsolva az autotípusra
- [x] Legyenek a foreign key-vel az autótípushoz akasztott táblák kaszkádolva úgy, hogyha a fajta/kategória/környezetvédelmi besorolás táblából törlünk valamit, akkor törlődjék automatikusan a hozzájuk tartozó autótípus recordok is.

**Comment by rajnaig1** [comment]
Mezők: 
Fajta:AUDI S8/Volkswagen Passat
Kinézet: Sedan/Kombi
Kategória: Személy/kisteher/teher/terepjáró/kisszemély
Prémium: Luxus
Hajtáslánc: benzin/diesel/elektromos
Váltótípus:Kézi/automata
Környezetvédelmi besorolás: E6 E5 etc
Évjárat: 2008
Teljesítmény: 8kW
Biztosítási díj: adott Ft
Súlyadó: számított Ft
Alapár: Idegen kulcs az árakra
Score: súlytényező az alapján, hogy mennyire akarják elpasszolni a kocsit
Minden AUDI S8 luxus, de van amelyik benzines, automata váltós, van diesel kéziváltós etc, azok különböznek, ergo az egyedi AUDI S8 típus tartalmazza ezeket az adatokat is

**Comment by NeilTomson** [comment]
mit vegyek fel az adatbázisba:
    Táblák száma:2
        Auto tipus:
            Márka
            Fajta
            Kategoria
            Prémium: Luxus
            Környezetvédelmi besorolás: E6 E5 etc
 
         
        Auto :
            Rendszám
            Alvázszám
            Hajtáslánc: benzin/diesel/elektromos
            Váltótípus:Kézi/automata
            Évjárat: 2008
            Teljesítmény: 8kW
            Biztosítási díj: adott Ft
             Km
            Állapot

**Comment by rajnaig1** [comment]
Ki kéne törlni a proba.html-t és a readme-t normálissá tenni.
